# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-14 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['profile_photo']},
        ),
    ]
